### ISSUE TITLE
Can this library run without connecting to the BitTorrent server？

### ISSUE THREAD

**Issue by Zjek** [naturalpolice/libdht#1]
Hello,@naturalpolice !
I want to create my own peer,and use first peer to contact with other peer.What should I do?

Thanks!

**Comment by naturalpolice** [comment]
Yes, it's kinda possible, although it won't work very well because of how Kademlia is supposed to work...

You can change the list of bootstrap nodes in the `bootstrap_hosts` array in nodes.c to include the IP address of the peer you know about.

The reason it won't work very well is that a DHT search can only finish when 8 or more nodes have responded, and these nodes are picked from the routing table that Kademlia constructs during the bootstrap process. The routing table is a list of "buckets" that can contain up to 8 different nodes each.
In order to function properly, your node must have been in contact of many other nodes. It is possible to build your own private DHT network but it will require a lot of nodes.
